export const SURAHS = [
    { number: 1, name: "Al-Fatiha", englishName: "The Opening", arabicName: "الفاتحة" },
    { number: 2, name: "Al-Baqarah", englishName: "The Cow", arabicName: "البقرة" },
    { number: 3, name: "Al-Imran", englishName: "The Family of Imran", arabicName: "آل عمران" },
    { number: 4, name: "An-Nisa", englishName: "The Women", arabicName: "النساء" },
    { number: 5, name: "Al-Ma'idah", englishName: "The Table Spread", arabicName: "المائدة" },
    { number: 6, name: "Al-An'am", englishName: "The Cattle", arabicName: "الأنعام" },
    { number: 7, name: "Al-A'raf", englishName: "The Heights", arabicName: "الأعراف" },
    { number: 8, name: "Al-Anfal", englishName: "The Spoils of War", arabicName: "الأنفال" },
    { number: 9, name: "At-Taubah", englishName: "The Repentance", arabicName: "التوبة" },
    { number: 10, name: "Yunus", englishName: "Jonah", arabicName: "يونس" },
    { number: 11, name: "Hud", englishName: "Hud", arabicName: "هود" },
    { number: 12, name: "Yusuf", englishName: "Joseph", arabicName: "يوسف" },
    { number: 13, name: "Ar-Ra'd", englishName: "The Thunder", arabicName: "الرعد" },
    { number: 14, name: "Ibrahim", englishName: "Abraham", arabicName: "إبراهيم" },
    { number: 15, name: "Al-Hijr", englishName: "The Rocky Tract", arabicName: "الحجر" },
    { number: 16, name: "An-Nahl", englishName: "The Bee", arabicName: "النحل" },
    { number: 17, name: "Al-Isra", englishName: "The Night Journey", arabicName: "الإسراء" },
    { number: 18, name: "Al-Kahf", englishName: "The Cave", arabicName: "الكهف" },
    { number: 19, name: "Maryam", englishName: "Mary", arabicName: "مريم" },
    { number: 20, name: "Ta-Ha", englishName: "Ta-Ha", arabicName: "طه" },
    { number: 21, name: "Al-Anbiya", englishName: "The Prophets", arabicName: "الأنبياء" },
    { number: 22, name: "Al-Hajj", englishName: "The Pilgrimage", arabicName: "الحج" },
    { number: 23, name: "Al-Mu'minun", englishName: "The Believers", arabicName: "المؤمنون" },
    { number: 24, name: "An-Nur", englishName: "The Light", arabicName: "النور" },
    { number: 25, name: "Al-Furqan", englishName: "The Criterion", arabicName: "الفرقان" },
    { number: 26, name: "Ash-Shu'ara", englishName: "The Poets", arabicName: "الشعراء" },
    { number: 27, name: "An-Naml", englishName: "The Ant", arabicName: "النمل" },
    { number: 28, name: "Al-Qasas", englishName: "The Stories", arabicName: "القصص" },
    { number: 29, name: "Al-Ankabut", englishName: "The Spider", arabicName: "العنكبوت" },
    { number: 30, name: "Ar-Rum", englishName: "The Romans", arabicName: "الروم" },
    { number: 31, name: "Luqman", englishName: "Luqman", arabicName: "لقمان" },
    { number: 32, name: "As-Sajdah", englishName: "The Prostration", arabicName: "السجدة" },
    { number: 33, name: "Al-Ahzab", englishName: "The Combined Forces", arabicName: "الأحزاب" },
    { number: 34, name: "Saba", englishName: "Sheba", arabicName: "سبأ" },
    { number: 35, name: "Fatir", englishName: "Originator", arabicName: "فاطر" },
    { number: 36, name: "Ya-Sin", englishName: "Ya Sin", arabicName: "يس" },
    { number: 37, name: "As-Saffat", englishName: "Those Who Set The Ranks", arabicName: "الصافات" },
    { number: 38, name: "Sad", englishName: "The Letter \"Saad\"", arabicName: "ص" },
    { number: 39, name: "Az-Zumar", englishName: "The Troops", arabicName: "الزمر" },
    { number: 40, name: "Ghafir", englishName: "The Forgiver", arabicName: "غافر" },
    { number: 41, name: "Fussilat", englishName: "Explained in Detail", arabicName: "فصلت" },
    { number: 42, name: "Ash-Shura", englishName: "The Consultation", arabicName: "الشورى" },
    { number: 43, name: "Az-Zukhruf", englishName: "The Ornaments of Gold", arabicName: "الزخرف" },
    { number: 44, name: "Ad-Dukhan", englishName: "The Smoke", arabicName: "الدخان" },
    { number: 45, name: "Al-Jathiyah", englishName: "The Crouching", arabicName: "الجاثية" },
    { number: 46, name: "Al-Ahqaf", englishName: "The Wind-Curved Sandhills", arabicName: "الأحقاف" },
    { number: 47, name: "Muhammad", englishName: "Muhammad", arabicName: "محمد" },
    { number: 48, name: "Al-Fath", englishName: "The Victory", arabicName: "الفتح" },
    { number: 49, name: "Al-Hujurat", englishName: "The Rooms", arabicName: "الحجرات" },
    { number: 50, name: "Qaf", englishName: "The Letter \"Qaf\"", arabicName: "ق" },
    { number: 51, name: "Ad-Dhariyat", englishName: "The Winnowing Winds", arabicName: "الذاريات" },
    { number: 52, name: "At-Tur", englishName: "The Mount", arabicName: "الطور" },
    { number: 53, name: "An-Najm", englishName: "The Star", arabicName: "النجم" },
    { number: 54, name: "Al-Qamar", englishName: "The Moon", arabicName: "القمر" },
    { number: 55, name: "Ar-Rahman", englishName: "The Beneficent", arabicName: "الرحمن" },
    { number: 56, name: "Al-Waqi'ah", englishName: "The Inevitable", arabicName: "الواقعة" },
    { number: 57, name: "Al-Hadid", englishName: "The Iron", arabicName: "الحديد" },
    { number: 58, name: "Al-Mujadila", englishName: "The Pleading Woman", arabicName: "المجادلة" },
    { number: 59, name: "Al-Hashr", englishName: "The Exile", arabicName: "الحشر" },
    { number: 60, name: "Al-Mumtahanah", englishName: "She that is to be examined", arabicName: "الممتحنة" },
    { number: 61, name: "As-Saff", englishName: "The Ranks", arabicName: "الصف" },
    { number: 62, name: "Al-Jumu'ah", englishName: "The Congregation, Friday", arabicName: "الجمعة" },
    { number: 63, name: "Al-Munafiqun", englishName: "The Hypocrites", arabicName: "المنافقون" },
    { number: 64, name: "At-Taghabun", englishName: "The Mutual Disillusion", arabicName: "التغابن" },
    { number: 65, name: "At-Talaq", englishName: "The Divorce", arabicName: "الطلاق" },
    { number: 66, name: "At-Tahrim", englishName: "The Prohibition", arabicName: "التحريم" },
    { number: 67, name: "Al-Mulk", englishName: "The Sovereignty", arabicName: "الملك" },
    { number: 68, name: "Al-Qalam", englishName: "The Pen", arabicName: "القلم" },
    { number: 69, name: "Al-Haqqah", englishName: "The Reality", arabicName: "الحاقة" },
    { number: 70, name: "Al-Ma'arij", englishName: "The Ascending Stairways", arabicName: "المعارج" },
    { number: 71, name: "Nuh", englishName: "Noah", arabicName: "نوح" },
    { number: 72, name: "Al-Jinn", englishName: "The Jinn", arabicName: "الجن" },
    { number: 73, name: "Al-Muzzammil", englishName: "The Enshrouded One", arabicName: "المزمل" },
    { number: 74, name: "Al-Muddaththir", englishName: "The Cloaked One", arabicName: "المدثر" },
    { number: 75, name: "Al-Qiyamah", englishName: "The Resurrection", arabicName: "القيامة" },
    { number: 76, name: "Al-Insan", englishName: "The Man", arabicName: "الإنسان" },
    { number: 77, name: "Al-Mursalat", englishName: "The Emissaries", arabicName: "المرسلات" },
    { number: 78, name: "An-Naba", englishName: "The Tidings", arabicName: "النبأ" },
    { number: 79, name: "An-Nazi'at", englishName: "Those who drag forth", arabicName: "النازعات" },
    { number: 80, name: "Abasa", englishName: "He Frowned", arabicName: "عبس" },
    { number: 81, name: "At-Takwir", englishName: "The Overthrowing", arabicName: "التكوير" },
    { number: 82, name: "Al-Infitar", englishName: "The Cleaving", arabicName: "الانفطار" },
    { number: 83, name: "Al-Mutaffifin", englishName: "The Defrauding", arabicName: "المطففين" },
    { number: 84, name: "Al-Inshiqaq", englishName: "The Sundering", arabicName: "الانشقاق" },
    { number: 85, name: "Al-Buruj", englishName: "The Mansions of the Stars", arabicName: "البروج" },
    { number: 86, name: "At-Tariq", englishName: "The Morning Star", arabicName: "الطارق" },
    { number: 87, name: "Al-A'la", englishName: "The Most High", arabicName: "الأعلى" },
    { number: 88, name: "Al-Ghashiyah", englishName: "The Overwhelming", arabicName: "الغاشية" },
    { number: 89, name: "Al-Fajr", englishName: "The Dawn", arabicName: "الفجر" },
    { number: 90, name: "Al-Balad", englishName: "The City", arabicName: "البلد" },
    { number: 91, name: "Ash-Shams", englishName: "The Sun", arabicName: "الشمس" },
    { number: 92, name: "Al-Lail", englishName: "The Night", arabicName: "الليل" },
    { number: 93, name: "Ad-Duha", englishName: "The Morning Hours", arabicName: "الضحى" },
    { number: 94, name: "Ash-Sharh", englishName: "The Relief", arabicName: "الشرح" },
    { number: 95, name: "At-Tin", englishName: "The Fig", arabicName: "التين" },
    { number: 96, name: "Al-Alaq", englishName: "The Clot", arabicName: "العلق" },
    { number: 97, name: "Al-Qadr", englishName: "The Power", arabicName: "القدر" },
    { number: 98, name: "Al-Bayyinah", englishName: "The Clear Proof", arabicName: "البينة" },
    { number: 99, name: "Az-Zalzalah", englishName: "The Earthquake", arabicName: "الزلزلة" },
    { number: 100, name: "Al-Adiyat", englishName: "The Courser", arabicName: "العاديات" },
    { number: 101, name: "Al-Qari'ah", englishName: "The Calamity", arabicName: "القارعة" },
    { number: 102, name: "At-Takathur", englishName: "The Rivalry in world increase", arabicName: "التكاثر" },
    { number: 103, name: "Al-Asr", englishName: "The Declining Day", arabicName: "العصر" },
    { number: 104, name: "Al-Humazah", englishName: "The Traducer", arabicName: "الهمزة" },
    { number: 105, name: "Al-Fil", englishName: "The Elephant", arabicName: "الفيل" },
    { number: 106, name: "Quraish", englishName: "Quraysh", arabicName: "قريش" },
    { number: 107, name: "Al-Ma'un", englishName: "The Small Kindness", arabicName: "الماعون" },
    { number: 108, name: "Al-Kawthar", englishName: "The Abundance", arabicName: "الكوثر" },
    { number: 109, name: "Al-Kafirun", englishName: "The Disbelievers", arabicName: "الكافرون" },
    { number: 110, name: "An-Nasr", englishName: "The Succour", arabicName: "النصر" },
    { number: 111, name: "Al-Masad", englishName: "The Palm Fiber", arabicName: "المسد" },
    { number: 112, name: "Al-Ikhlas", englishName: "The Sincerity", arabicName: "الإخلاص" },
    { number: 113, name: "Al-Falaq", englishName: "The Daybreak", arabicName: "الفلق" },
    { number: 114, name: "An-Nas", englishName: "Mankind", arabicName: "الناس" }
];

export const RECITERS = [
    { id: "ar.alafasy", name: "Mishary Rashid Alafasy", arabicName: "مشاري راشد العفاسي" },
    { id: "ar.abdulbasitmurattal", name: "Abdul Basit (Murattal)", arabicName: "عبد الباسط عبد الصمد (مرتل)" },
    { id: "ar.abdullahbasfar", name: "Abdullah Basfar", arabicName: "عبد الله بصفر" },
    { id: "ar.abdurrahmaansudais", name: "Abdurrahmaan As-Sudais", arabicName: "عبد الرحمن السديس" },
    { id: "ar.abdulsamad", name: "Abdul Samad", arabicName: "عبد الصمد" },
    { id: "ar.shaatree", name: "Abu Bakr Ash-Shaatree", arabicName: "أبو بكر الشاطري" },
    { id: "ar.ahmedajamy", name: "Ahmed ibn Ali al-Ajamy", arabicName: "أحمد بن علي العجمي" },
    { id: "ar.hanirifai", name: "Hani Rifai", arabicName: "هاني الرفاعي" },
    { id: "ar.husary", name: "Husary", arabicName: "الحصري" },
    { id: "ar.husarymujawwad", name: "Husary (Mujawwad)", arabicName: "الحصري (مجود)" },
    { id: "ar.hudhaify", name: "Hudhaify", arabicName: "الحذيفي" },
    { id: "ar.ibrahimakhbar", name: "Ibrahim Akhdar", arabicName: "إبراهيم الأخضر" },
    { id: "ar.mahermuaiqly", name: "Maher Al Muaiqly", arabicName: "ماهر المعيقلي" },
    { id: "ar.muhammadayyoub", name: "Muhammad Ayyoub", arabicName: "محمد أيوب" },
    { id: "ar.muhammadjibreel", name: "Muhammad Jibreel", arabicName: "محمد جبريل" },
    { id: "ar.saoodshuraym", name: "Saood bin Ibraaheem Ash-Shuraym", arabicName: "سعود الشريم" },
    { id: "ar.parhizgar", name: "Parhizgar", arabicName: "برهيزكار" },
    { id: "ar.aymanswoaid", name: "Ayman Sowaid", arabicName: "أيمن سويد" }
];
