export const SURAHS = [
    { number: 1, name: "Al-Fatiha", englishName: "The Opening", arabicName: "الفاتحة", ayahs: 7 },
    { number: 2, name: "Al-Baqarah", englishName: "The Cow", arabicName: "البقرة", ayahs: 286 },
    { number: 3, name: "Al-Imran", englishName: "The Family of Imran", arabicName: "آل عمران", ayahs: 200 },
    { number: 4, name: "An-Nisa", englishName: "The Women", arabicName: "النساء", ayahs: 176 },
    { number: 5, name: "Al-Ma'idah", englishName: "The Table Spread", arabicName: "المائدة", ayahs: 120 },
    { number: 6, name: "Al-An'am", englishName: "The Cattle", arabicName: "الأنعام", ayahs: 165 },
    { number: 7, name: "Al-A'raf", englishName: "The Heights", arabicName: "الأعراف", ayahs: 206 },
    { number: 8, name: "Al-Anfal", englishName: "The Spoils of War", arabicName: "الأنفال", ayahs: 75 },
    { number: 9, name: "At-Taubah", englishName: "The Repentance", arabicName: "التوبة", ayahs: 129 },
    { number: 10, name: "Yunus", englishName: "Jonah", arabicName: "يونس", ayahs: 109 },
    { number: 11, name: "Hud", englishName: "Hud", arabicName: "هود", ayahs: 123 },
    { number: 12, name: "Yusuf", englishName: "Joseph", arabicName: "يوسف", ayahs: 111 },
    { number: 13, name: "Ar-Ra'd", englishName: "The Thunder", arabicName: "الرعد", ayahs: 43 },
    { number: 14, name: "Ibrahim", englishName: "Abraham", arabicName: "إبراهيم", ayahs: 52 },
    { number: 15, name: "Al-Hijr", englishName: "The Rocky Tract", arabicName: "الحجر", ayahs: 99 },
    { number: 16, name: "An-Nahl", englishName: "The Bee", arabicName: "النحل", ayahs: 128 },
    { number: 17, name: "Al-Isra", englishName: "The Night Journey", arabicName: "الإسراء", ayahs: 111 },
    { number: 18, name: "Al-Kahf", englishName: "The Cave", arabicName: "الكهف", ayahs: 110 },
    { number: 19, name: "Maryam", englishName: "Mary", arabicName: "مريم", ayahs: 98 },
    { number: 20, name: "Ta-Ha", englishName: "Ta-Ha", arabicName: "طه", ayahs: 135 },
    { number: 21, name: "Al-Anbiya", englishName: "The Prophets", arabicName: "الأنبياء", ayahs: 112 },
    { number: 22, name: "Al-Hajj", englishName: "The Pilgrimage", arabicName: "الحج", ayahs: 78 },
    { number: 23, name: "Al-Mu'minun", englishName: "The Believers", arabicName: "المؤمنون", ayahs: 118 },
    { number: 24, name: "An-Nur", englishName: "The Light", arabicName: "النور", ayahs: 64 },
    { number: 25, name: "Al-Furqan", englishName: "The Criterion", arabicName: "الفرقان", ayahs: 77 },
    { number: 26, name: "Ash-Shu'ara", englishName: "The Poets", arabicName: "الشعراء", ayahs: 227 },
    { number: 27, name: "An-Naml", englishName: "The Ant", arabicName: "النمل", ayahs: 93 },
    { number: 28, name: "Al-Qasas", englishName: "The Stories", arabicName: "القصص", ayahs: 88 },
    { number: 29, name: "Al-Ankabut", englishName: "The Spider", arabicName: "العنكبوت", ayahs: 69 },
    { number: 30, name: "Ar-Rum", englishName: "The Romans", arabicName: "الروم", ayahs: 60 },
    { number: 31, name: "Luqman", englishName: "Luqman", arabicName: "لقمان", ayahs: 34 },
    { number: 32, name: "As-Sajdah", englishName: "The Prostration", arabicName: "السجدة", ayahs: 30 },
    { number: 33, name: "Al-Ahzab", englishName: "The Combined Forces", arabicName: "الأحزاب", ayahs: 73 },
    { number: 34, name: "Saba", englishName: "Sheba", arabicName: "سبأ", ayahs: 54 },
    { number: 35, name: "Fatir", englishName: "Originator", arabicName: "فاطر", ayahs: 45 },
    { number: 36, name: "Ya-Sin", englishName: "Ya Sin", arabicName: "يس", ayahs: 83 },
    { number: 37, name: "As-Saffat", englishName: "Those Who Set The Ranks", arabicName: "الصافات", ayahs: 182 },
    { number: 38, name: "Sad", englishName: "The Letter \"Saad\"", arabicName: "ص", ayahs: 88 },
    { number: 39, name: "Az-Zumar", englishName: "The Troops", arabicName: "الزمر", ayahs: 75 },
    { number: 40, name: "Ghafir", englishName: "The Forgiver", arabicName: "غافر", ayahs: 85 },
    { number: 41, name: "Fussilat", englishName: "Explained in Detail", arabicName: "فصلت", ayahs: 54 },
    { number: 42, name: "Ash-Shura", englishName: "The Consultation", arabicName: "الشورى", ayahs: 53 },
    { number: 43, name: "Az-Zukhruf", englishName: "The Ornaments of Gold", arabicName: "الزخرف", ayahs: 89 },
    { number: 44, name: "Ad-Dukhan", englishName: "The Smoke", arabicName: "الدخان", ayahs: 59 },
    { number: 45, name: "Al-Jathiyah", englishName: "The Crouching", arabicName: "الجاثية", ayahs: 37 },
    { number: 46, name: "Al-Ahqaf", englishName: "The Wind-Curved Sandhills", arabicName: "الأحقاف", ayahs: 35 },
    { number: 47, name: "Muhammad", englishName: "Muhammad", arabicName: "محمد", ayahs: 38 },
    { number: 48, name: "Al-Fath", englishName: "The Victory", arabicName: "الفتح", ayahs: 29 },
    { number: 49, name: "Al-Hujurat", englishName: "The Rooms", arabicName: "الحجرات", ayahs: 18 },
    { number: 50, name: "Qaf", englishName: "The Letter \"Qaf\"", arabicName: "ق", ayahs: 45 },
    { number: 51, name: "Ad-Dhariyat", englishName: "The Winnowing Winds", arabicName: "الذاريات", ayahs: 60 },
    { number: 52, name: "At-Tur", englishName: "The Mount", arabicName: "الطور", ayahs: 49 },
    { number: 53, name: "An-Najm", englishName: "The Star", arabicName: "النجم", ayahs: 62 },
    { number: 54, name: "Al-Qamar", englishName: "The Moon", arabicName: "القمر", ayahs: 55 },
    { number: 55, name: "Ar-Rahman", englishName: "The Beneficent", arabicName: "الرحمن", ayahs: 78 },
    { number: 56, name: "Al-Waqi'ah", englishName: "The Inevitable", arabicName: "الواقعة", ayahs: 96 },
    { number: 57, name: "Al-Hadid", englishName: "The Iron", arabicName: "الحديد", ayahs: 29 },
    { number: 58, name: "Al-Mujadila", englishName: "The Pleading Woman", arabicName: "المجادلة", ayahs: 22 },
    { number: 59, name: "Al-Hashr", englishName: "The Exile", arabicName: "الحشر", ayahs: 24 },
    { number: 60, name: "Al-Mumtahanah", englishName: "She that is to be examined", arabicName: "الممتحنة", ayahs: 13 },
    { number: 61, name: "As-Saff", englishName: "The Ranks", arabicName: "الصف", ayahs: 14 },
    { number: 62, name: "Al-Jumu'ah", englishName: "The Congregation, Friday", arabicName: "الجمعة", ayahs: 11 },
    { number: 63, name: "Al-Munafiqun", englishName: "The Hypocrites", arabicName: "المنافقون", ayahs: 11 },
    { number: 64, name: "At-Taghabun", englishName: "The Mutual Disillusion", arabicName: "التغابن", ayahs: 18 },
    { number: 65, name: "At-Talaq", englishName: "The Divorce", arabicName: "الطلاق", ayahs: 12 },
    { number: 66, name: "At-Tahrim", englishName: "The Prohibition", arabicName: "التحريم", ayahs: 12 },
    { number: 67, name: "Al-Mulk", englishName: "The Sovereignty", arabicName: "الملك", ayahs: 30 },
    { number: 68, name: "Al-Qalam", englishName: "The Pen", arabicName: "القلم", ayahs: 52 },
    { number: 69, name: "Al-Haqqah", englishName: "The Reality", arabicName: "الحاقة", ayahs: 52 },
    { number: 70, name: "Al-Ma'arij", englishName: "The Ascending Stairways", arabicName: "المعارج", ayahs: 44 },
    { number: 71, name: "Nuh", englishName: "Noah", arabicName: "نوح", ayahs: 28 },
    { number: 72, name: "Al-Jinn", englishName: "The Jinn", arabicName: "الجن", ayahs: 28 },
    { number: 73, name: "Al-Muzzammil", englishName: "The Enshrouded One", arabicName: "المزمل", ayahs: 20 },
    { number: 74, name: "Al-Muddaththir", englishName: "The Cloaked One", arabicName: "المدثر", ayahs: 56 },
    { number: 75, name: "Al-Qiyamah", englishName: "The Resurrection", arabicName: "القيامة", ayahs: 40 },
    { number: 76, name: "Al-Insan", englishName: "The Man", arabicName: "الإنسان", ayahs: 31 },
    { number: 77, name: "Al-Mursalat", englishName: "The Emissaries", arabicName: "المرسلات", ayahs: 50 },
    { number: 78, name: "An-Naba", englishName: "The Tidings", arabicName: "النبأ", ayahs: 40 },
    { number: 79, name: "An-Nazi'at", englishName: "Those who drag forth", arabicName: "النازعات", ayahs: 46 },
    { number: 80, name: "Abasa", englishName: "He Frowned", arabicName: "عبس", ayahs: 42 },
    { number: 81, name: "At-Takwir", englishName: "The Overthrowing", arabicName: "التكوير", ayahs: 29 },
    { number: 82, name: "Al-Infitar", englishName: "The Cleaving", arabicName: "الانفطار", ayahs: 19 },
    { number: 83, name: "Al-Mutaffifin", englishName: "The Defrauding", arabicName: "المطففين", ayahs: 36 },
    { number: 84, name: "Al-Inshiqaq", englishName: "The Sundering", arabicName: "الانشقاق", ayahs: 25 },
    { number: 85, name: "Al-Buruj", englishName: "The Mansions of the Stars", arabicName: "البروج", ayahs: 22 },
    { number: 86, name: "At-Tariq", englishName: "The Morning Star", arabicName: "الطارق", ayahs: 17 },
    { number: 87, name: "Al-A'la", englishName: "The Most High", arabicName: "الأعلى", ayahs: 19 },
    { number: 88, name: "Al-Ghashiyah", englishName: "The Overwhelming", arabicName: "الغاشية", ayahs: 26 },
    { number: 89, name: "Al-Fajr", englishName: "The Dawn", arabicName: "الفجر", ayahs: 30 },
    { number: 90, name: "Al-Balad", englishName: "The City", arabicName: "البلد", ayahs: 20 },
    { number: 91, name: "Ash-Shams", englishName: "The Sun", arabicName: "الشمس", ayahs: 15 },
    { number: 92, name: "Al-Lail", englishName: "The Night", arabicName: "الليل", ayahs: 21 },
    { number: 93, name: "Ad-Duha", englishName: "The Morning Hours", arabicName: "الضحى", ayahs: 11 },
    { number: 94, name: "Ash-Sharh", englishName: "The Relief", arabicName: "الشرح", ayahs: 8 },
    { number: 95, name: "At-Tin", englishName: "The Fig", arabicName: "التين", ayahs: 8 },
    { number: 96, name: "Al-Alaq", englishName: "The Clot", arabicName: "العلق", ayahs: 19 },
    { number: 97, name: "Al-Qadr", englishName: "The Power", arabicName: "القدر", ayahs: 5 },
    { number: 98, name: "Al-Bayyinah", englishName: "The Clear Proof", arabicName: "البينة", ayahs: 8 },
    { number: 99, name: "Az-Zalzalah", englishName: "The Earthquake", arabicName: "الزلزلة", ayahs: 8 },
    { number: 100, name: "Al-Adiyat", englishName: "The Courser", arabicName: "العاديات", ayahs: 11 },
    { number: 101, name: "Al-Qari'ah", englishName: "The Calamity", arabicName: "القارعة", ayahs: 11 },
    { number: 102, name: "At-Takathur", englishName: "The Rivalry in world increase", arabicName: "التكاثر", ayahs: 8 },
    { number: 103, name: "Al-Asr", englishName: "The Declining Day", arabicName: "العصر", ayahs: 3 },
    { number: 104, name: "Al-Humazah", englishName: "The Traducer", arabicName: "الهمزة", ayahs: 9 },
    { number: 105, name: "Al-Fil", englishName: "The Elephant", arabicName: "الفيل", ayahs: 5 },
    { number: 106, name: "Quraish", englishName: "Quraysh", arabicName: "قريش", ayahs: 4 },
    { number: 107, name: "Al-Ma'un", englishName: "The Small Kindness", arabicName: "الماعون", ayahs: 7 },
    { number: 108, name: "Al-Kawthar", englishName: "The Abundance", arabicName: "الكوثر", ayahs: 3 },
    { number: 109, name: "Al-Kafirun", englishName: "The Disbelievers", arabicName: "الكافرون", ayahs: 6 },
    { number: 110, name: "An-Nasr", englishName: "The Succour", arabicName: "النصر", ayahs: 3 },
    { number: 111, name: "Al-Masad", englishName: "The Palm Fiber", arabicName: "المسد", ayahs: 5 },
    { number: 112, name: "Al-Ikhlas", englishName: "The Sincerity", arabicName: "الإخلاص", ayahs: 4 },
    { number: 113, name: "Al-Falaq", englishName: "The Daybreak", arabicName: "الفلق", ayahs: 5 },
    { number: 114, name: "An-Nas", englishName: "Mankind", arabicName: "الناس", ayahs: 6 }
];

export const RECITERS = [
    { id: "ar.alafasy", name: "Mishary Rashid Alafasy", arabicName: "مشاري راشد العفاسي" },
    { id: "ar.abdulbasitmurattal", name: "Abdul Basit (Murattal)", arabicName: "عبد الباسط عبد الصمد (مرتل)" },
    { id: "ar.abdullahbasfar", name: "Abdullah Basfar", arabicName: "عبد الله بصفر" },
    { id: "ar.abdurrahmaansudais", name: "Abdurrahmaan As-Sudais", arabicName: "عبد الرحمن السديس" },
    { id: "ar.abdulsamad", name: "Abdul Samad", arabicName: "عبد الصمد" },
    { id: "ar.shaatree", name: "Abu Bakr Ash-Shaatree", arabicName: "أبو بكر الشاطري" },
    { id: "ar.ahmedajamy", name: "Ahmed ibn Ali al-Ajamy", arabicName: "أحمد بن علي العجمي" },
    { id: "ar.hanirifai", name: "Hani Rifai", arabicName: "هاني الرفاعي" },
    { id: "ar.husary", name: "Husary", arabicName: "الحصري" },
    { id: "ar.husarymujawwad", name: "Husary (Mujawwad)", arabicName: "الحصري (مجود)" },
    { id: "ar.hudhaify", name: "Hudhaify", arabicName: "الحذيفي" },
    { id: "ar.ibrahimakhbar", name: "Ibrahim Akhdar", arabicName: "إبراهيم الأخضر" },
    { id: "ar.mahermuaiqly", name: "Maher Al Muaiqly", arabicName: "ماهر المعيقلي" },
    { id: "ar.muhammadayyoub", name: "Muhammad Ayyoub", arabicName: "محمد أيوب" },
    { id: "ar.muhammadjibreel", name: "Muhammad Jibreel", arabicName: "محمد جبريل" },
    { id: "ar.saoodshuraym", name: "Saood bin Ibraaheem Ash-Shuraym", arabicName: "سعود الشريم" },
    { id: "ar.parhizgar", name: "Parhizgar", arabicName: "برهيزكار" },
    { id: "ar.aymanswoaid", name: "Ayman Sowaid", arabicName: "أيمن سويد" }
];
